### ISSUE TITLE
一堆问题！！！！！！！！！！！！

### ISSUE THREAD

**Issue by LongC-CN** [MiaoFile/TCB_Minecraft#1]
1.定价严重不平衡！！！！！
(1)原版矿石价格严重偏高
(2)粘液物品与矿石价格严重偏低
(3)领地价格与商店相比严重偏低
(4)出售与收购价格相差过大（钻石收购与出售相差4倍）
2.没有添加扫地插件，杀死怪物掉落的金钱无法消除
3.汉化问题
(1)ess没有汉化（修改config.yml中的locale: en 将en改为zh)
`
# Set the locale for all messages.
# If you don't set this, the default locale of the server will be used.
# For example, to set language to English, set locale to en, to use the file "mess$
# Don't forget to remove the # in front of the line.
# For more information, visit http://wiki.ess3.net/wiki/Locale
locale: zh
`
(2)许多物品没有汉化（建议添加ProtocolStringReplacer插件可以在不修改插件的情况下直接修改文字内容）
(3)被反作弊踢出服务器的提示没有汉化
4.权限问题
(1)Quickshop无法创建大商店和修改价格
(2)/warps没有权限，没有指明warp的创建条件
5.反作弊的物品移动的限制过于严格，java无法使用快捷键快速移动物品（多次尝试还会踢出服务器）
6.龙蛋呢？

**Comment by znc15** [comment]
将于二周目重构
